from .start import start
from .current_tariff import current_tariff
from .pay import pay
from .refs import refs
from .referal import referal
from .settings import settings
from .support import support
from .tariffs import tariffs
from .torrent_question import torrent_question
from .torrent_question_yes import torrent_question_yes
from .torrent_question_no import torrent_question_no
